export const START_MONITORING  = 'START_MONITORING';
export const PAUSE_MONITORING  = 'PAUSE_MONITORING';
export const STOP_MONITORING  = 'STOP_MONITORING';
export const APPLICATIONS_LIST  = 'APPLICATIONS_LIST';
export const MONITOR_APP_LOG = 'MONITOR_APP_LOG';
export const SET_HOST = 'SET_HOST';
export const LOGS_MESSAGES = 'LOGS_MESSAGES'